# process.on('uncaughtException', console.error) // safe log error 
